### ISSUE TITLE
windows_clipboard: pass string as ref

### ISSUE THREAD

**Issue by DoumanAsh** [aweinstock314/rust-clipboard#13]
https://github.com/aweinstock314/rust-clipboard/blob/master/src/windows_clipboard.rs#L16

No need to create OsString explicitly here.
You can just pass it as reference as this function accepts `AsRef<OsString>`

JFYI or maybe i misunderstood your intention here :)

**Comment by aweinstock314** [comment]
You're correct, thanks for the suggestion.
