### ISSUE TITLE
Publish 0.1.2 to crates.io

### ISSUE THREAD

**Issue by SSheldon** [aweinstock314/rust-clipboard#32]
The latest version on crates.io is 0.1.1, which unfortunately uses an older version of `objc` that will fail to compile after rust-lang/rust#34198.

`objc` was updated in #24, so all we have to do is push that change to crates.io and crater will stop reporting this crate as a regression :)

**Comment by aweinstock314** [comment]
It's updated: https://crates.io/crates/clipboard/0.1.2

**Comment by SSheldon** [comment]
Awesome, thank you! 😊
