### ISSUE TITLE
Prepare to update clipboard-win

### ISSUE THREAD

**Issue by DoumanAsh** [aweinstock314/rust-clipboard#35]
Hello,

I started re-writing API for clipboard-win.
More or less i have unified it, added [Clipboard](https://docs.rs/clipboard-win/2.0.0-pre.1/x86_64-pc-windows-msvc/clipboard_win/struct.Clipboard.html) class and improved a bit a way i was extracting clipboard data(using `GlobalSize` instead of `strlen`)

It is for now `pre1` as i'm still considering a way to make API better and waiting for new version of winapi.
Feel free to take a look and have suggestions on API changes.

**Comment by aweinstock314** [comment]
Looks good. Can you verify that https://github.com/aweinstock314/rust-clipboard/tree/winclip2 compiles before I push to master? (I don't currently have access to any Windows boxen to test on.)

**Comment by DoumanAsh** [comment]
Yep, it compiles.
