### ISSUE TITLE
Write a non-GPL'd X11ClipboardContext

### ISSUE THREAD

**Issue by aweinstock314** [aweinstock314/rust-clipboard#38]
Currently, `X11ClipboardContext` is a straightforward port of `xclip`, which is GPL2. That means that this crate has to be GPL2, which makes it unsuited to its original purpose (see https://github.com/servo/servo/commit/ecabb1823b7531944be755e192acf0b7a9b2e698), as well as less likely to be adopted by the Rust ecosystem (e.g. https://github.com/jwilm/alacritty/blob/master/copypasta/src/x11.rs#L5-L6). The current licensing situation also seems potentially confusing (see issue #33). The current code also has some heisenbugs that seem to be a result of UB (see issue #25), but with nothing obvious jumping out, a rewrite also has a chance of fixing this.

https://tronche.com/gui/x/icccm/sec-2.html seems to be the primary documentation on what The Right Thing for the protocol should be.
http://invisible-island.net/xterm/xterm.html looks to have a permissive (BSD/MIT style) license, and is a real-world piece of code that can be referred to for how it's done in practice.

The overall architecture currently involves spawning threads instead of forking, which results in the clipboard not persisting past the end of the main thread. This was done due to potential deadlock concerns on systems that don't use `pthread_atfork` hooks in their malloc implementations, based on the comment at https://github.com/rust-lang/rust/blob/ee60afa09465cedfa08be04e59b6a8ccfd54685f/src/libstd/sys/unix/process/process_unix.rs#L114-L143. Now that the types have been refactored (`X11ClipboardContext` is a seperate type from `ClipboardContext`), it might make sense to fork-by-default, but leave an option in the constructor fall back to threads if anyone's experiencing deadlocks in practice (this could maybe use some more thought).

Another issue with the current code is that it doesn't correctly handle concurrent requests (it drops all subsequent ones, following `xclip`'s design choices). Since the protocol can be treated as a state machine, it should be easy (from a not-ported-from-C perspective) to store a HashMap<RequestIdentifier /* probably *mut Window? */, RequestStateMachine> to handle concurrent requests. This sort of design will also facilitate adding bells-and-whistles like 2.2's "More advanced selection owners are free to maintain a history of the value of the selection and to respond to requests for the value of the selection during periods they owned it even though they do not own it now."

Rewriting `X11ClipboardContext` would fix the majority of the outstanding issues on this crate, and is a blocker for the remaining one (i.e. making a least-common-denominator API for typed data), as it doesn't make sense to duplicate the work of implementing that feature on code that's planned to be rewritten anyway.

**Comment by quininer** [comment]
I try to use xcb to implement it. https://github.com/quininer/x11-clipboard

**Comment by aweinstock314** [comment]
Looks like a good start. The use of `xcb` looks like it'll be possible for your implementation to have no uses of `unsafe`, which'll probably help with avoiding bugs like issue #25.

Is the eventual intent for your code to be merged into `rust-clipboard` once it reaches feature-parity with the current implementation, or for `rust-clipboard` to contain a wrapper that calls into your crate?

**Comment by quininer** [comment]
I will open a PR after the completion, but I am now a little busy. :)

It should be a separate crate because `alacritty` need.
