### ISSUE TITLE
Getting Err value on provider.get_contents().unwrap()

### ISSUE THREAD

**Issue by uglyluigi** [aweinstock314/rust-clipboard#66]
The (WindowsClipboardContext) clipboard provider, on calling get_contents(), returns an Err value with code 0 and a message saying "The operation completed successfully." This makes it impossible to unwrap() the contents and use them although the clipboard provider appears to have successfully captured the clipboard.

Windows 10, Rust 2018 edition.

**Comment by kovaxis** [comment]
I believe this happens when the clipboard is empty.
